#!/usr/bin/env bash
source "$MASTEROPS_HOME/cli/lib/common.sh"
source "$MASTEROPS_HOME/lib/select.sh"
source "$MASTEROPS_HOME/lib/catalog.sh"
source "$MASTEROPS_HOME/lib/db_mode.sh"

PROJECT_NAME=""
PRESET_NAME=""

for arg in "$@"; do
  case "$arg" in
    --preset=*) PRESET_NAME="${arg#--preset=}" ;;
    -*) mops_die "unknown flag: $arg" ;;
    *) [[ -z "$PROJECT_NAME" ]] && PROJECT_NAME="$arg" ;;
  esac
done

[[ -z "$PROJECT_NAME" ]] && mops_die "usage: masterops new <project> [--preset=<name>]"

PROJECT_DIR="$MOPS_PROJECTS_DIR/$PROJECT_NAME"
mops_ensure_dir "$PROJECT_DIR"

STACKS=()

if [[ -n "$PRESET_NAME" ]]; then
  # --- Preset mode: read stacks from the preset file, as before ---
  PRESET_FILE="$MASTEROPS_HOME/presets/${PRESET_NAME}.yaml"
  [[ -f "$PRESET_FILE" ]] || mops_die "preset not found: $PRESET_NAME"

  mapfile -t STACKS < <(sed -n '/^stacks:/,/^[^ ]/p' "$PRESET_FILE" | grep '^\s*- ' | sed 's/^\s*-\s*//')
  [[ "${#STACKS[@]}" -eq 0 ]] && mops_die "preset $PRESET_NAME has no stacks"

  mops_log "scaffolding '$PROJECT_NAME' from preset '$PRESET_NAME'"
else
  # --- Interactive mode: ask the engineer, layer by layer ---
  mops_log "scaffolding '$PROJECT_NAME' interactively (no preset)"

  backend_stack=$(choose_backend_stack)
  [[ -n "$backend_stack" ]] && STACKS+=("$backend_stack")

  frontend_stack=$(choose_frontend_stack)
  [[ -n "$frontend_stack" ]] && STACKS+=("$frontend_stack")

  webserver_stack=$(choose_webserver_stack)
  [[ -n "$webserver_stack" ]] && STACKS+=("$webserver_stack")

  database_stack=$(choose_database_stack)
  [[ -n "$database_stack" ]] && STACKS+=("$database_stack")

  if [[ "${#STACKS[@]}" -eq 0 ]]; then
    mops_warn "no stacks selected -- project will be scaffolded empty"
  fi

  PRESET_NAME="interactive"
fi

mops_log "stacks: ${STACKS[*]:-none}"

COMPOSE_FILE="$PROJECT_DIR/docker-compose.yml"
ENV_FILE="$PROJECT_DIR/.env.example"

{
  echo "# Generated by masterops from preset: $PRESET_NAME"
  echo "# Nothing here is started automatically. Run: masterops start <service>"
  echo "version: \"3.9\""
  echo "services:"
} > "$COMPOSE_FILE"

: > "$ENV_FILE"
echo "PROJECT_NAME=$PROJECT_NAME" >> "$ENV_FILE"

VOLUMES=()
NATIVE_DB_STACKS=()

for stack in "${STACKS[@]}"; do
  stack_dir="$MASTEROPS_HOME/stacks/$stack"
  [[ -d "$stack_dir" ]] || { mops_warn "stack not found, skipping: $stack"; continue; }

  # Every layer (not just database) can be container / native / skip.
  # Use the stack's own path as a human-readable label in the prompt.
  install_mode=$(select_install_mode "$stack")

  if [[ "$install_mode" == "skip" ]]; then
    mops_warn "skipped: $stack (choose later)"
    continue
  fi

  if [[ "$install_mode" == "native" ]]; then
    if [[ -f "$stack_dir/install-native.sh" ]]; then
      if [[ "$stack" == database/* ]]; then
        # Database native installs need the merged .env file to read
        # credentials from, and run after all layers are collected
        # (see the post-processing loop below).
        NATIVE_DB_STACKS+=("$stack")
      else
        mops_log "installing $stack natively on this server..."
        bash "$stack_dir/install-native.sh" || mops_warn "native install failed for $stack -- scaffold continues; retry manually: bash $stack_dir/install-native.sh"
      fi
    else
      mops_warn "$stack has no install-native.sh, falling back to container"
      install_mode="container"
    fi
  fi

  if [[ "$install_mode" == "container" ]] && [[ -f "$stack_dir/compose.fragment.yml" ]]; then
    cat "$stack_dir/compose.fragment.yml" >> "$COMPOSE_FILE"
    mops_ok "added service: $stack"
  fi

  if [[ -f "$stack_dir/.env.example" ]]; then
    echo "" >> "$ENV_FILE"
    echo "# --- $stack ---" >> "$ENV_FILE"
    cat "$stack_dir/.env.example" >> "$ENV_FILE"
  fi

  case "$stack" in
    backend/*)
      mops_ensure_dir "$PROJECT_DIR/backend"
      [[ -f "$stack_dir/Dockerfile" ]] && cp --update=none "$stack_dir/Dockerfile" "$PROJECT_DIR/backend/Dockerfile"
      ;;
    frontend/*)
      mops_ensure_dir "$PROJECT_DIR/frontend"
      [[ -f "$stack_dir/Dockerfile" ]] && cp --update=none "$stack_dir/Dockerfile" "$PROJECT_DIR/frontend/Dockerfile"
      ;;
  esac
done

if grep -q "postgres:" "$COMPOSE_FILE"; then VOLUMES+=("postgres_data:"); fi
if [[ "${#VOLUMES[@]}" -gt 0 ]]; then
  echo "volumes:" >> "$COMPOSE_FILE"
  for v in "${VOLUMES[@]}"; do echo "  $v" >> "$COMPOSE_FILE"; done
fi

# Post-process: for any DB installed natively, run its post-install setup
# (create DB/user/password from .env.example), fix DB_HOST to localhost,
# and strip depends_on references + empty depends_on blocks left behind.
for stack in "${NATIVE_DB_STACKS[@]}"; do
  db_name="${stack#database/}"
  stack_dir="$MASTEROPS_HOME/stacks/$stack"

  mops_log "installing $db_name natively on this server..."
  bash "$stack_dir/install-native.sh" "$ENV_FILE" || mops_warn "native install failed for $stack -- scaffold continues; retry manually: bash $stack_dir/install-native.sh $ENV_FILE"

  sed -i "s/^DB_HOST=${db_name}\$/DB_HOST=127.0.0.1/" "$ENV_FILE"
  sed -i "/^\\s*-\\s*${db_name}\\s*$/d" "$COMPOSE_FILE"

  python3 - "$COMPOSE_FILE" << 'PYCLEAN'
import sys
path = sys.argv[1]
with open(path) as f:
    lines = f.readlines()
out = []
i = 0
while i < len(lines):
    line = lines[i]
    if line.strip() == "depends_on:":
        j = i + 1
        has_child = j < len(lines) and lines[j].startswith("    -")
        if not has_child:
            i += 1
            continue
    out.append(line)
    i += 1
with open(path, "w") as f:
    f.writelines(out)
PYCLEAN
done

cat > "$PROJECT_DIR/masterops.yaml" << PROJEOF
project: $PROJECT_NAME
preset: $PRESET_NAME
generated_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)
stacks:
$(for s in "${STACKS[@]}"; do echo "  - $s"; done)
PROJEOF

mops_ok "project scaffolded at: $PROJECT_DIR"
mops_log "next: cd $PROJECT_NAME && cp .env.example .env"
