---
- name: Scaffold Angular Project
  block:
    - name: Install Angular CLI
      ansible.builtin.shell:
        cmd: "npm install -g @angular/cli"

    - name: Create project directory
      ansible.builtin.file:
        path: "{{ project_path }}/frontend"
        state: directory
        owner: "{{ ansible_user | default(ansible_env.USER) }}"
        mode: '0755'

    - name: Create Angular project
      ansible.builtin.shell:
        cmd: "ng new {{ project_name }}-frontend --routing --style css"
        chdir: "{{ project_path }}/frontend"
      become_user: "{{ ansible_user | default(ansible_env.USER) }}"
      args:
        creates: "{{ project_path }}/frontend/{{ project_name }}-frontend/package.json"

    - name: Build Angular application
      ansible.builtin.shell:
        cmd: "npm run build"
        chdir: "{{ project_path }}/frontend/{{ project_name }}-frontend"
      become_user: "{{ ansible_user | default(ansible_env.USER) }}"
